Feat/adherent
elucas0/la-palme-verte pull request #5
Opened 2023-09-24 14:24 UTC by aspenne

new feature adherent

2023-09-24 14:32 UTC, HeineZo commented on src/app/adherent/components/BecomeMember.component.tsx
>   * @param className Classe tailwind à ajouter *(optionnel)*
t'as rajouter des props mais t'as pas mis leur doc

2023-09-24 14:34 UTC, HeineZo commented on src/app/blog/page.tsx
> +export default function page() {
doc de la page

2023-09-24 14:53 UTC, HeineZo requested changes

2023-09-24 14:53 UTC, HeineZo commented on src/app/blog/page.tsx
> +  ];
les icônes sont pas dans le même ordre que sur figma

2023-09-24 14:53 UTC, HeineZo commented on src/app/blog/page.tsx
> +        subtitle={'Pourquoi pas vous ?'}
```suggestion
        title='84 personnes ont déjà rejoint l’association'
        subtitle='Pourquoi pas vous ?'
```

2023-09-24 14:53 UTC, HeineZo commented on src/app/blog/page.tsx
> +      </div>
Tu devrais utiliser la classe `section` qui est dispo dans le `globals.css`, elle permet d'avoir une marge plus petite en mobile sinon ça rend un truc chelou comme ça 
![image](https://github.com/elucas0/la-palme-verte/assets/85509892/66857ea1-8616-4ae9-8a7f-705182339b76)

2023-09-24 14:53 UTC, HeineZo commented on src/app/blog/page.tsx
> +    </section>
pareil dcp pour la classe `section`

2023-09-24 14:53 UTC, HeineZo commented on src/app/page.tsx
> +      >
faute d'inattention
```suggestion
      <BecomeMember 
        title="Devenez adhérent pour rejoindre une communauté grandissante"
        shortTitle="Devenez adhérent"
        subtitle="En adhérant à l'association, vous pourrez participer à nos actions et
          nous aider à protéger la biodiversité marine."
      >
```

2023-09-24 14:53 UTC, HeineZo commented on src/app/blog/page.tsx
> +    <div>
est-ce qu'il vaudrait pas mieux mettre `<section>` en tant que balise principale du fichier, et `<div>` en tant que blocs dans le fichier ?

2023-09-24 14:53 UTC, HeineZo commented on src/shared/layout/Navbar.layout.tsx
> +            {pages.adherent.label}
mais du coup là c'est plus "Devenir adhérent` mais `Adhérent` ?

2023-09-24 14:53 UTC, HeineZo commented on structure.json
>    }
peut-être remplacer `adherent `par `other` ou un truc dans le genre comme ça on pourrait y mettre les CGU etc..

2023-09-25 17:41 UTC, aspenne commented on src/app/blog/page.tsx
> +      </div>
euhh elle est déjà là non ?

2023-09-25 18:29 UTC, HeineZo commented on src/app/blog/page.tsx
> +      </div>
ah oui j'avais pas vu, mais tu met un `p-16 ` juste avant du coup ça overirde je pense

2023-09-26 13:27 UTC, merged